	$(document).ready(function(){
				$(".sgn").hide();
		$(".sgn_up").click(function(){
		$(".sgn").show();
		});
		$(".cancel").click(function(){
		$(".sgn").hide();	
		});
		$(".submit").click(function(){
		$(".sgn").hide();
		});
		});